version: "3"
services:
  frontend:
    container_name: WaitingLine
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4000:4000'

  backend:
    build: ./backend
    image: backend
    ports:
      - 3333:3333
    environment:
      CONFIG_MYSQL_DATABASE: WaitingLinedb
      CONFIG_MYSQL_USER: root
      CONFIG_MYSQL_PASSWORD: secret
      CONFIG_MYSQL_HOST: db
      # from the backend, connect to MySQL via the "db" hostname on port 3306
      CONFIG_MYSQL_PORT: 3306
    depends_on:
      - db
    restart: always

  db:
    container_name: db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_HOST_IP: db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cookbookdb
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "11000:8000"
      - "13306:3306"
    restart: always

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "3029:80"
    environment:
      PMA_USER: root
      PMA_PASSWORD: secret
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    
