version: "3"
services:
  frontend:
    container_name: WaitingLine
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4000:4000'

  backend:
    build: ./backend
    image: backend
    ports:
      - 3333:3333
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_SERVER=localhost
    links:
     - postgres  

  postgres:
    container_name: postgresdb
    image: postgres:10.5
    environment:
      - POSTGRES_DB:WaitingList
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
          options:
            max-size: 10m
            max-file: "3"
    ports:
      - "5432:5432"
    volumes: 
          - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
      container_name: pgadmin_container
      image: dpage/pgadmin4

      environment:
        PGADMIN_DEFAULT_EMAIL: admin@waitinglist.com
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_CONFIG_SERVER_MODE: 'False'

      volumes:
        - pgadmin:/var/lib/pgadmin

      ports:
        - "5050:80"
      networks:
        - postgres
      restart: unless-stopped

networks:
    postgres:
      driver: bridge

volumes:
      postgres:
      pgadmin:
    
