apiVersion: v1
kind: Service
metadata:
  name: fastapi-test-service
spec:
  selector:
    app: fastapi-test-app
  ports:
  - protocol: "TCP"
    port: 3333
    targetPort: 3333
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-test-app
spec:
  selector:
    matchLabels:
      app: fastapi-test-app
  replicas: 2
  template:
    metadata:
      labels:
        app: fastapi-test-app
    spec:
      containers:
      - name: fastapi-test-app
        image: fastapi-kubernetes
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3333